Changes to support ci_build/install scripts with Ubuntu 18.04 docker containers
Switched from clang-format-3.8 to clang-format-3.9, as it is available on
Ubuntu 18.04, in addition to being available on Ubuntu 14.04 and Ubuntu 16.04.

python-setuptools in Ubuntu 18.04 no longer includes easy_install. For Ubuntu
18.04 only, installing pip using the https://bootstrap.pypa.io/get-pip.py
python program. Ubuntu 16.04 and 14.04 behavior unchanged.

Force installing lazy-object-proxy version 1.4.1, because non x86_64 systems
that need to compile from source encounter an error with version 1.4.2:
AttributeError: module 'setuptools.build_meta' has no attribute '__legacy__'
This error is because we install setuptools with apt, and then replace
setuptools with a newer version using pip. This error is resolved in the latest
version of setuptools.